# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capybara-facebook}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathieu Fosse"]
  s.date = %q{2010-03-26}
  s.description = %q{Facebook Driver for Capybara}
  s.email = %q{mathieu@tigerlilyapps.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config.ru",
     "lib/capybara-facebook.rb",
     "lib/capybara-facebook/cucumber.rb",
     "lib/capybara-facebook/driver/base.rb",
     "lib/capybara-facebook/driver/facebook_driver.rb",
     "lib/capybara-facebook/session.rb",
     "spec/driver/facebook_driver_spec.rb",
     "spec/drivers_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/test_app.rb",
     "spec/views/buttons.erb",
     "spec/views/fieldsets.erb",
     "spec/views/form.erb",
     "spec/views/postback.erb",
     "spec/views/tables.erb",
     "spec/views/with_html.erb",
     "spec/views/with_js.erb",
     "spec/views/with_scope.erb",
     "spec/views/with_simple_html.erb"
  ]
  s.homepage = %q{http://github.com/pointcom/capybara-facebook}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Facebook Driver for Capybara}
  s.test_files = [
    "spec/driver/facebook_driver_spec.rb",
     "spec/drivers_spec.rb",
     "spec/spec_helper.rb",
     "spec/test_app.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<capybara>, [">= 0.3.5"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<capybara>, [">= 0.3.5"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<capybara>, [">= 0.3.5"])
  end
end

